import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const packageJson = JSON.parse(
  readFileSync(resolve(repositoryRoot, "package.json"), "utf8"),
);

function clean(value) {
  const normalized = typeof value === "string" ? value.trim() : "";
  return normalized || undefined;
}

function git(...args) {
  try {
    return clean(
      execFileSync("git", args, {
        cwd: repositoryRoot,
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      }),
    );
  } catch {
    return undefined;
  }
}

const commit =
  clean(process.env.HANDRAIL_BUG_REPORTER_SDK_COMMIT) ??
  git("rev-parse", "HEAD");
if (!commit || !/^(?:[0-9a-f]{40}|[0-9a-f]{64})$/i.test(commit)) {
  throw new Error(
    "A full Git commit is required. Set HANDRAIL_BUG_REPORTER_SDK_COMMIT when building outside a Git checkout.",
  );
}
const exactTag = git("describe", "--exact-match", "--tags", commit);
const canonicalVersionTag = `v${packageJson.version}`;
const releaseRef =
  clean(process.env.HANDRAIL_BUG_REPORTER_SDK_REF) ??
  (exactTag === canonicalVersionTag ? `refs/tags/${exactTag}` : undefined) ??
  `commit:${commit}`;
if (
  !/^(?:refs\/tags\/\S+|commit:(?:[0-9a-f]{40}|[0-9a-f]{64})|(?:[0-9a-f]{40}|[0-9a-f]{64})|v?\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?)$/i.test(
    releaseRef,
  )
) {
  throw new Error(
    `HANDRAIL_BUG_REPORTER_SDK_REF must identify an immutable tag or commit; received ${JSON.stringify(releaseRef)}.`,
  );
}

const generated = `// Generated by scripts/generate-release.mjs. Do not edit.\n` +
  `export const GENERATED_PACKAGE_NAME = ${JSON.stringify(packageJson.name)} as const;\n` +
  `export const GENERATED_PACKAGE_VERSION = ${JSON.stringify(packageJson.version)} as const;\n` +
  `export const GENERATED_PACKAGE_COMMIT = ${JSON.stringify(commit)} as const;\n` +
  `export const GENERATED_PACKAGE_RELEASE_REF = ${JSON.stringify(releaseRef)} as const;\n`;

const output = resolve(repositoryRoot, "src/generated/release.ts");
mkdirSync(dirname(output), { recursive: true });
writeFileSync(output, generated, "utf8");
