import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  assertReleaseIdentity,
  assertReleaseManifests,
  resolveReleaseRef,
} from "./release-contract.mjs";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const packageJson = JSON.parse(
  readFileSync(resolve(repositoryRoot, "package.json"), "utf8"),
);
const packageLock = JSON.parse(
  readFileSync(resolve(repositoryRoot, "package-lock.json"), "utf8"),
);
assertReleaseManifests(packageJson, packageLock);

function clean(value) {
  const normalized = typeof value === "string" ? value.trim() : "";
  return normalized || undefined;
}

function git(...args) {
  try {
    return clean(
      execFileSync("git", args, {
        cwd: repositoryRoot,
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      }),
    );
  } catch {
    return undefined;
  }
}

const commit =
  clean(process.env.HANDRAIL_BUG_REPORTER_SDK_COMMIT) ??
  git("rev-parse", "HEAD");
const exactTag = git("describe", "--exact-match", "--tags", commit);
const releaseRef = resolveReleaseRef({
  commit,
  exactTag,
  explicitRef: clean(process.env.HANDRAIL_BUG_REPORTER_SDK_REF),
  version: packageJson.version,
});
assertReleaseIdentity(
  {
    commit,
    packageName: packageJson.name,
    packageVersion: packageJson.version,
    releaseRef,
  },
  packageJson,
);

const generated = `// Generated by scripts/generate-release.mjs. Do not edit.\n` +
  `export const GENERATED_PACKAGE_NAME = ${JSON.stringify(packageJson.name)} as const;\n` +
  `export const GENERATED_PACKAGE_VERSION = ${JSON.stringify(packageJson.version)} as const;\n` +
  `export const GENERATED_PACKAGE_COMMIT = ${JSON.stringify(commit)} as const;\n` +
  `export const GENERATED_PACKAGE_RELEASE_REF = ${JSON.stringify(releaseRef)} as const;\n`;

const output = resolve(repositoryRoot, "src/generated/release.ts");
mkdirSync(dirname(output), { recursive: true });
writeFileSync(output, generated, "utf8");
